import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";


const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      
      className={`${notoSansBengali.className} h-full antialiased`}
    >
      <body className="min-h-full">
        <Navbar></Navbar>
        {children}
        
      </body>
    </html>
  );
}
